# Generated by Django 6.0 on 2025-12-30 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviewmodel_stars_alter_reviewmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='stars',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.ManyToManyField(blank=True, to='product.reviewmodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel'),
        ),
    ]
